name: DoggyRelics
version: 1.0.0
description: Your plugin description here
main: com.doggyrelics.DoggyRelics
api-version: 1.19
authors: [Dogfall]
website: https://yourpluginwebsite.com
depend: []

commands:
  relics:
    description: Description of your command
    usage: /relics
    permission: relics.command.permission

permissions:
  relics.command.permission:
    description: Permission to use /relics  # Corrected the command name
