#Hey there! This is the config file of the SendConsoleMessage plugin. Please configure it to your hearts content :)

#If you get any errors or something doesnt work as expected, please check the console and please make sure there aren't any problems with the yaml formatting
#You can check YAML formatting with this page https://yaml-online-parser.appspot.com/

#If the plugin is still acting up, please reach out at the plugin discussion and I'll give you a hand :)
#${project.url}
#---------------------------------------------------------------------------------------------------------------------------------------------------------------

#Should the plugin be activated?
enabled: true

CommandName: SendConsoleMessage

#Permission required to use the command:
PermissionRequired: sendConsoleMessage.sendMessage

#All the alternative commands to send a console message.
CommandAliases:
  - scm
  - scmsg
  - consolemessage
  
#The prefix that will appear before the message on the console will be whatever you write inside the "", or nothing if you leave it as it is.
ConsoleMessagePrefix: ""

#Should bStats remain enabled? bStats sends annonymous data about the server, helping us feel motivated and make more informed decisions about the plugin's future. You can find all the information collected here : https://bstats.org/plugin/bukkit/ExplosionKnockdown/9738
bStats: true